"""llm.py — generates grounded answers using the DeepSeek API.

Receives a natural-language question and retrieved code context, then asks
DeepSeek to answer using only that supplied context.
"""

import os

from dotenv import load_dotenv
from openai import OpenAI, OpenAIError

load_dotenv()

DEEPSEEK_BASE_URL = "https://api.deepseek.com"
LLM_MODEL = "deepseek-v4-flash"

SYSTEM_PROMPT = (
    "You are a codebase assistant. "
    "Answer the user's question using only the provided code context. "
    "If the context does not contain enough information to answer reliably, "
    "say that the available code context is insufficient. "
    "Do not invent implementation details."
)


def get_deepseek_client() -> OpenAI:
    """Creates an authenticated client for the DeepSeek API.

    Returns:
        An OpenAI-compatible client configured to send requests to DeepSeek.

    Raises:
        RuntimeError: If DEEPSEEK_API_KEY is not available in the environment.
    """
    api_key = os.getenv("DEEPSEEK_API_KEY")

    if not api_key:
        raise RuntimeError(
            "DEEPSEEK_API_KEY is not set. Add it to the .env file."
        )

    return OpenAI(
        api_key=api_key,
        base_url=DEEPSEEK_BASE_URL,
    )


def generate_answer(question: str, context: str) -> str:
    """Generates an answer grounded in retrieved code context.

    Args:
        question: Natural-language question about the indexed codebase.
        context: Retrieved source-code chunks to use as grounding information.

    Returns:
        The answer generated by DeepSeek.

    Raises:
        ValueError: If the question or context is empty.
        RuntimeError: If DeepSeek returns an empty response.
    """
    if not question.strip():
        raise ValueError("Question cannot be empty.")

    if not context.strip():
        raise ValueError("Context cannot be empty.")

    client = get_deepseek_client()

    # Keep instructions separate from the user question and retrieved code.
    user_message = (
        f"CODE CONTEXT:\n{context}\n\n"
        f"QUESTION:\n{question}"
    )

    try:
        # Send the grounded question and code context to DeepSeek.
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
            stream=False,
        )

    except OpenAIError as error:
        # Hide provider-specific errors from the rest of the application.
        raise RuntimeError(
            "DeepSeek request failed."
        ) from error

    answer = response.choices[0].message.content

    if not answer:
        raise RuntimeError("DeepSeek returned an empty response.")

    return answer


if __name__ == "__main__":
    test_context = """
Source: example.py:1-2

def add(a, b):
    return a + b
"""

    test_question = "What does the add function do?"

    print(generate_answer(test_question, test_context))